proton-tkg/proton-tkg.sh, wine-tkg-git/non-makepkg-build.sh
When an external config path is passed to proton-tkg.sh or non-makepkg-build.sh, and it doesn't exist, we should bail early, so that the user knows that they screwed up the path.
We don't want them puzzling over what went wrong during building, or with the build, if it completed, so alert them immediately.
=> Bail on a non-existent passed external config path, instead of blindly forging ahead without the user's awareness

wine-tkg-git/PKGBUILD
When doing a clean installation on Arch Linux, it does not do the installation of VKD3D, see that in the PKGBUILD file was the selection of TRUE when it is already "mainline", but I do not know how the Fork installation will take
=> Change from True to Mainline in VKD3D

.gitignore, wine-tkg-git/customization.cfg, wine-tkg-git/wine-tkg-profiles/sample-external-config.cfg, wine-tkg-git/wine-tkg-profiles/wine-tkg.cfg, wine-tkg-git/wine-tkg-scripts/build.sh, wine-tkg-git/wine-tkg-scripts/package-debian.sh, wine-tkg-git/wine-tkg-scripts/wine-tkg-interactive, wine-tkg-git/wine-tkg-scripts/wine64-tkg
This allows wine-tkg to create debian packages on arch
Can be enabled with _GENERATE_DEBIAN_PACKAGE in config
TODO: Support different prefixes than /usr
TODO FIX: Make wine64-tkg the default as "wine64", the problem is it causes wine to complain about wine64 (invalid ELF header I think)
I didn't fully test this, but winecfg and wine explorer.exe works.
Hope this will be useful for people using Debian-based distros
=> wine-tkg: Debian packaging on Arch

wine-tkg-git/wine-tkg-scripts/prepare.sh
Fixes output of `wine --version` not showing version tags, which in turn fixes various checks in Lutris.
=> Fix version tags not getting applied.

proton-tkg/proton-tkg-profiles/sample-external-config.cfg, proton-tkg/proton-tkg.cfg, proton-tkg/proton-tkg.sh
So this adds `$_use_dxvk="latest"` option which downloads latest job artifact of master branch from git.froggi.es as a zip file (I can't find tar file there).
Might be a good idea to consider having it as the default option rather than release being the default as I think it would fit proton-tkg as it's already using development wine, staging for example (at least by default).
=> proton-tkg: DXVK artifact build support (from git.froggi.es)

wine-tkg-git/PKGBUILD
Fixes cases like 'protonified' preset, which produce a package
named 'wine-tkg-git-protonified', and then have a replaces that
points at the same package name, which does funny things when
you add builds to a custom repo, like constantly asking you to
re-download and re-install the package.
=> Add package name check to replaces declaration

proton-tkg/PKGBUILD
Looks like it's needed for vrclient build otherwise vrclient build fails on `<vulkan/vulkan.h>` include (and then steam fails to launch games with proton-tkg)
=> Proton-tkg: Add vulkan-headers as make dependency

proton-tkg/proton-tkg-profiles/sample-external-config.cfg, proton-tkg/proton-tkg.cfg, proton-tkg/proton-tkg.sh
git.froggi.es was changed from GitLab to Gitea and no longer has DXVK artifacts
=> proton-tkg: Remove "latest" DXVK option which downloads from git.froggi.es

wine-tkg-git/wine-tkg-patches/game-specific/ffxiv-launcher-workaround.patch
FFXIV patch was broken due to the extensive changes that have happened with ntdll over the past many months.
This small fix should make that go away. Until it breaks again...
I don't know what commit the current FFXIV patch successfully applies to, and I don't know how to figure that out, so can I leave that to you? frog_donut
=> Update FFXIV patch so it works again

wine-tkg-git/wine-tkg-patches/hotfixes/earlyhotfixer
Skips some patches if they've already been patched in the Wine version selected.
The point of this is to avoid patching errors and make the patching process smoother.
=> Improve comments and skip some patches in the earlyhotfixer script.

wine-tkg-git/wine-tkg-patches/hotfixes/earlyhotfixer
Skips the Add-SORT_DIGITSAS-UMBERS-flag-to-CompareStringsEx patch if the commit that fixes it is in the Wine version selected.
The upstream commit and the patch are not the same, but the commit still adds everything the patch does, plus some extra stuff.
=> Skip another patch.

.github/workflows/proton-arch.yml, proton-tkg/proton-tkg.sh
It builds well after this small change.
Here action:
<details> <summary>proton-arch.yml</summary> 
``` yaml
name: Proton Arch Linux CI
on:
workflow_dispatch:
jobs:
build:
runs-on: ubuntu-latest
container: archlinux:latest
steps:
- uses: actions/checkout@v2
- name: Compile
run: |
echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
pacman -Syu --noconfirm base-devel sudo lib32-jack2
useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
chown user -R ..
chown user -R /tmp
export CARGO_HOME="$PWD"
cd proton-tkg
su user -c "yes ''|PKGDEST=/tmp/proton-tkg makepkg --noconfirm -s"
- name: Archive the artifacts
uses: actions/upload-artifact@v2
with:
name: proton-tkg-build
path: /tmp/proton-tkg
```
=> fix wine_is_running function hang when CI used

wine-tkg-git/wine-tkg-patches/hotfixes/08cccb5/08cccb5.mypatch, wine-tkg-git/wine-tkg-patches/hotfixes/08cccb5/a608ef1.mypatch, wine-tkg-git/wine-tkg-patches/hotfixes/hotfixer
This error was triggered by the unity crash reporter.
I tried and tested the patch before posting the pull request, and I can say the error reporter is no longer crashing...  
I can't say the same thing for the game.
I know it's not a lot but I hope it helps.
Also since I saw you liked to support old wine versions, I tried to make it support old versions too.
=> Hotfixer: Remove a TRACE in the DXGIGetDebugInterface1 stub causing segfaults.

wine-tkg-git/wine-tkg-patches/misc/lowlatency_audio_pulse.patch, wine-tkg-git/wine-tkg-profiles/wine-tkg-osu.cfg, wine-tkg-git/wine-tkg-scripts/prepare.sh
- Added `wine-tkg-git/wine-tkg-patches/misc/lowlatency_audio_pulse.patch`.
- Modified `wine-tkg-osu.cfg` profile to use `_lowlatency_audio_pulse=true`.
- Updated `wine-tkg-git/wine-tkg-scripts/prepare.sh` to support `_lowlatency_audio_pulse` configuration.
> The patch is applied only if [f77af3dd632](https://github.com/wine-mirror/wine/commit/f77af3dd6324fadaf153062d77b51f755f71faea) is applied to current HEAD, which is the earliest commit that the patch applies.
This patch works for both PulseAudio and Pipewire.
=> Add low latency pulse/pipewire patch stolen from ThePoon

wine-tkg-git/wine-tkg-patches/proton/fsync_futex_waitv.patch
Adds https://gist.github.com/ivyl/93107ffef32b2e8816d1176286afdd12
This will not make it possible to keep multiple interfaces (unchanged) in the same kernel build, it just adds safe futex_waitv disabling for kernels with old futex2 interface.
=> Improve fsync_futex_waitv patch compatibility

wine-tkg-git/PKGBUILD, wine-tkg-git/wine-tkg-profiles/advanced-customization.cfg, wine-tkg-git/wine-tkg-profiles/sample-external-config.cfg
A mechanism to mirror existing `_user_makedeps`; allows to create packages that require additional dependencies at both buildtime and runtime, as defined by user's custom configuration.
Useful for cases like:
```bash
_use_vkd3dlib="true"
_configure_userargs64="${_configure_userargs64} --with-vkd3d"
_configure_userargs32="${_configure_userargs32} --with-vkd3d"
_user_deps="${_user_deps} vkd3d lib32-vkd3d"
```
or
```bash
_configure_userargs64="${_configure_userargs64} --with-gcrypt"
_configure_userargs32="${_configure_userargs32} --with-gcrypt"
_user_deps="${_user_deps} libgcrypt lib32-libgcrypt"
```
or
```bash
_community_patches="${_community_patches} wine_wayland_driver.mypatch"
_user_makedeps="${_user_makedeps} wayland-protocols"
_user_deps="${_user_deps} libxkbcommon lib32-libxkbcommon" …
```
=> Allow users to add custom runtime dependencies

wine-tkg-git/wine-tkg-patches/hotfixes/memset/memset.mypatch, wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg-staging.patch, wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg.patch
This fixes is necessary for the correct applying of the of memset-fix on older versions where it was required.
And adds missing parts for proton-tkg after 1dbbc803ac5dc138e4362b6555a786296f2b1f0b
=> split memset-fix

wine-tkg-git/wine-tkg-scripts/prepare.sh
This patch attempts to make the logic of locating/creating `community-packages` repo root more reliable, especially in `makechrootpkg` environment.
=> Make community-patches logic play nicely with makechrootpkg

wine-tkg-git/wine-tkg-patches/proton/fsync_futex_waitv.patch
I hope these small changes will be enough to solve the problem of building Wine-TkG in different build environments, and as I expect this should help solve the same problem with some future packages in Archlinux build environments.
Fixes https://github.com/Frogging-Family/wine-tkg-git/issues/643
=> futex_waitv: Add check for linux futex header

wine-tkg-git/wine-tkg-patches/hotfixes/hotfixer
This PR fixes a script syntax error introduced in https://github.com/Frogging-Family/wine-tkg-git/commit/f5b6ca3e7afb18dc9e8ffa16c8a035593b668e00 :frog: :heart:
closes #667
=> Fix syntax error in hotfixer

wine-tkg-git/customization.cfg, wine-tkg-git/wine-tkg-scripts/prepare.sh
Allows skipping the automatic `git pull` on the `community-patches` directory during wine/proton build. Useful for people with a fork of it.
=> add _community_patches_auto_update setting

wine-tkg-git/wine-tkg-patches/misc/fastsync/fastsync-staging.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/fastsync-staging-e534d65.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/fastsync-staging-protonify-e534d65.patch, wine-tkg-git/wine-tkg-scripts/prepare.sh
update due to https://github.com/wine-staging/wine-staging/commit/e534d6546a5be9f1cd53a0ea3ac79db7d977bed7
=> Update fastsync patches for e534d65 and move previous versions to legacy

wine-tkg-git/customization.cfg, wine-tkg-git/wine-tkg-patches/proton/shared-gpu-resources/shared-gpu-resources, wine-tkg-git/wine-tkg-patches/proton/shared-gpu-resources/sharedgpures-fixup.patch, wine-tkg-git/wine-tkg-patches/proton/shared-gpu-resources/sharedgpures-mfplat.patch, wine-tkg-git/wine-tkg-patches/proton/shared-gpu-resources/sharedgpures.patch, wine-tkg-git/wine-tkg-profiles/sample-external-config.cfg, wine-tkg-git/wine-tkg-scripts/prepare.sh
"Add initial support for shared gpu resources.
Disabled by default since these patches are only in **Proton Experimental**.
Requires DXVK 1.10.3+, VKD3D-Proton 2.7+"
https://github.com/doitsujin/dxvk/pull/2516
https://github.com/doitsujin/dxvk/pull/2608
these patches are enough to make video work in `Neighbors Back From Hell` (Unity engine)
https://github.com/ValveSoftware/wine/commit/649717ad0a34e07886fd2568623b5e33b2a875f3:
```
With this and the previous two patches, some video playback bugs
are solved for some games (e.g. Trailmakers, Rustler, TOHU and
others) when using DXVK (wined3d doesn't currently support
shared resources, so there is no way to check with it).
```
but maybe other videos will need more patches from Giovanni Mascellani related to CW-Bug-Id: **#19126**
UPD. added …
=> Add shared gpu resources patchset

wine-tkg-git/wine-tkg-patches/proton/shared-gpu-resources/sharedgpures-fences-fshack.patch, wine-tkg-git/wine-tkg-patches/proton/shared-gpu-resources/sharedgpures-fences.patch, wine-tkg-git/wine-tkg-patches/proton/shared-gpu-resources/sharedgpures-texture.patch
This part of the old code was mistakenly taken from deprecated branch https://github.com/Guy1524/wine/tree/shared-resources and now interferes.
Fixes the launch of probably most Vulkan games. (Hades [vulkan] still broken like on current `experimental_7.0`.)
=> sharedgpures: Fix shared gpu resources patchset

wine-tkg-git/wine-tkg-patches/proton/shared-gpu-resources/legacy/sharedgpures-fixup-76db4b2.patch, wine-tkg-git/wine-tkg-patches/proton/shared-gpu-resources/sharedgpures-fixup.patch
Sorry, I couldn't take the time to resolve it properly right away, but @Guy1524 explained that it's enough to just resolve the conflicts. Less code, should be more maintainable.
Also sharedgpures-fixup is not intended to contain absolutely all Media Foundation source related fixes, but only some proton-specific CW-Bug-Id: **#19126** patches, which probably cannot be accepted in the current state to Upstream, but since https://github.com/wine-mirror/wine/commit/76db4b2459920eb2e2004255e3388b069dd1d6f9 already exists, let em be in sharedgpures-fixup-76db4b2
=> sharedgpures: Discard avoidable reverts

wine-tkg-git/wine-tkg-patches/proton/shared-gpu-resources/legacy/sharedgpures-fences-e553be7.patch, wine-tkg-git/wine-tkg-patches/proton/shared-gpu-resources/legacy/sharedgpures-textures-395061e.patch, wine-tkg-git/wine-tkg-patches/proton/shared-gpu-resources/legacy/sharedgpures-textures-e553be7.patch, wine-tkg-git/wine-tkg-patches/proton/shared-gpu-resources/shared-gpu-resources, wine-tkg-git/wine-tkg-patches/proton/shared-gpu-resources/sharedgpures-fences-fshack.patch, wine-tkg-git/wine-tkg-patches/proton/shared-gpu-resources/sharedgpures-fences.patch
This commit based on work of @llde (The same as https://github.com/Frogging-Family/wine-tkg-git/pull/861, but avoided monolithic style patches and splitting redesign. But, as I said before, because of such significant changes, it is likely that if any problems arise, it will first be necessary to additionally check that this is not due to the influence of a rebase.)
resolves https://github.com/Frogging-Family/wine-tkg-git/issues/860
Apart from this, minor changes (that I have long wanted to do): slightly more respect patch separation, more cleanup for non-fshack version and fix some compilation warning (for legacy versions also where is it possible).
=> sharedgpures: Rebase sharedgpures patches for e553be7 and move previous version to legacy

wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg/mainline/legacy/proton-tkg-22fa68b.patch, wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg/mainline/legacy/proton-tkg-8dd04c7.patch, wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg/mainline/legacy/proton-tkg-dfd5f10.patch, wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg/mainline/legacy/proton-tkg-fefe108.patch, wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg/mainline/proton-tkg.patch, wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg/proton-tkg, wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg/proton-tkg-additions.patch, wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg/staging/legacy/proton-tkg-staging-22fa68b.patch, wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg/staging/legacy/proton-tkg-staging-8dd04c7.patch, wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg/staging/legacy/proton-tkg-staging-dfd5f10.patch, wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg/staging/legacy/proton-tkg-staging-fefe108.patch, wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg/staging/proton-tkg-staging.patch
Allows running Forza Horizon 4/5 with wine-tkg.
A few patches from the FS hack (although not directly related to that functionality) rebased to the latest Wine tree and added as an additional patch. The patch only applies on _protonify and inactive _proton_fs_hack. That way the games can be used without the FS hack and also avoid all the reverts :).
=> Protonify: Fix some issues and add a few additional patches mostly needed for Forza Horizon games.

wine-tkg-git/README.md
Link is outdated, or is there some other link that should be used?
=> Remove Ubuntu Docker notice from wine-tkg-git/

wine-tkg-git/wine-tkg-patches/hotfixes/autoconf-opencl-hotfix/hotfixes, wine-tkg-git/wine-tkg-patches/hotfixes/autoconf-opencl-hotfix/opencl-fixup.mypatch, wine-tkg-git/wine-tkg-patches/hotfixes/hotfixer, wine-tkg-git/wine-tkg-scripts/prepare.sh
Hi. As  I was writing on discord yesterday, currently wine-tkg doesn't call tools/make_makefiles however it seems to include at least one patch that cause doesn't properly include the configure.ac changes. 
This can be seen after the preparation step by using the following commands in the wine_mirror-git folder
git add * (to add all files to git )
git commit -m "base"  (create a base commit)
./tools/make_makefiles
git diff
It's possible to see various changes around nv* dlls (this is with staging, protonify, sharedgpures), a sign it wasn't updated properly before
The change in this PR also allow to use properly patchset that doesn't properly provide configure.ac modifications for added or modified dlls. And also allow  is to remove most of the configure/configure.ac parts of the …
=> [wine-tkg] Call tool/make_makefile after userpatch application, plus a autoconf fix

README.md
An option to download nightly builds without logging in would be better, but in this way there is at least an explanation.
=> Add explanation why nightly builds can't be downloaded for users that are not logged in

wine-tkg-git/wine-tkg-profiles/advanced-customization.cfg, wine-tkg-git/wine-tkg-scripts/Makefile.single, wine-tkg-git/wine-tkg-scripts/build-32.sh, wine-tkg-git/wine-tkg-scripts/build-64.sh, wine-tkg-git/wine-tkg-scripts/build.sh
This allows building 64-bit and 32-bit Wine in parallel, using GNU Make's jobserver to limit the number of processes.
Reason: Some parts of Wine (e.g. actxprxy_shobjidl_p.c) take quite long to compile with high optimization flags, it would be nice if those parts wouldn't effectively halt the compilation process.
The name of the variable may be a little bit wrong, since we are actually starting multiple `make` processes, but there's only one jobserver. Eh, whatever.
=> Implement single-make mode

.gitignore
This might affect other directories too, but I'm only interested in fixing this one.
If I find any other directories that need to be ignored, I'll make another MR including them.
=> Fix the gitignore not ignoring wine-tkg-git/src

proton-tkg/proton-tkg-profiles/sample-external-config.cfg, proton-tkg/proton-tkg.cfg, proton-tkg/proton-tkg.sh, proton-tkg/proton_template/conf/proton, proton-tkg/proton_template/conf/user_settings.py, wine-tkg-git/customization.cfg, wine-tkg-git/wine-tkg-patches/misc/fastsync/fastsync, wine-tkg-git/wine-tkg-patches/misc/fastsync/fastsync-mainline.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/fastsync-staging-protonify.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/fastsync-staging.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/fastsync-mainline-f076e5f.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/fastsync-staging-e534d65.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/fastsync-staging-protonify-e534d65.patch, wine-tkg-git/wine-tkg-profiles/sample-external-config.cfg, wine-tkg-git/wine-tkg-scripts/build.sh, wine-tkg-git/wine-tkg-scripts/prepare.sh
- "immediately prevent building without winesync header"
if `_use_fastsync="true"` was set, we probably don't want to run into fastsync not working on _that_ build of Wine. No need to waste time compiling such builds.
- "not make conflicts fail-safe, stop the build immediately"
The same as the previous one. With `_use_fastsync="true"` we want the Wine build with Fastsync. So let's save the User time and let them start resolving conflicts _before_ compiling.
- "output terminal message if `/dev/winesync` not exist"
Sometimes people forget that they haven't loaded the winesync module. _Numerous_ complaints from fastsync should clear things up _a bit_.
- "make priority over fsync/esync (it's **NOT** failsafe, like fsync!)."
any `WINEESYNC` and `WINEFSYNC` values will be completely ignored …
=> fastsync: Add some "QoL things" for testers

wine-tkg-git/wine-tkg-patches/proton/shared-gpu-resources/legacy/sharedgpures-fences-c65bfc0.patch, wine-tkg-git/wine-tkg-patches/proton/shared-gpu-resources/shared-gpu-resources, wine-tkg-git/wine-tkg-patches/proton/shared-gpu-resources/sharedgpures-fences.patch
Hi, using the excuse of the (luckly mild) earthquake that happened I made an important hotfix for shared gpu resouce patchset.
Basically  32 bit thunk conversion were converting VkCommandBuffer to native handles in every case they were involved in structure conversion bypassing original conversion functions and unwrapping needs (probably becouse they took the need_conversion True path as they are dispatchable), so they were unwrapped also when Thunk Type wasn't Public. This error depended on make_vulkan script. 64 bit thunks weren't affected.
This was causing an assertion in 32 bit application using DXVK.  Added a comment inside make_vulkan.
Doesn't seems other error of this sort are present inside the thunks.
Also added the fences patchset for the 7.20 patchset I forgot to include and to …
=> Hotfix for shared gpu resources

proton-tkg/proton-tkg-profiles/legacy/legacy-options.cfg, proton-tkg/proton-tkg-profiles/sample-external-config.cfg, proton-tkg/proton-tkg.cfg, wine-tkg-git/customization.cfg, wine-tkg-git/wine-tkg-patches/proton/fsync/fsync, wine-tkg-git/wine-tkg-profiles/legacy/legacy-options.cfg, wine-tkg-git/wine-tkg-profiles/sample-external-config.cfg, wine-tkg-git/wine-tkg-profiles/wine-tkg-mainline.cfg, wine-tkg-git/wine-tkg-profiles/wine-tkg-staging.cfg, wine-tkg-git/wine-tkg-scripts/build.sh, wine-tkg-git/wine-tkg-scripts/prepare.sh
enough time has passed, so there should be no more problems associated with the transition to using futex_waitv.
this PR should clean up some the fsync things:
- for [the main fsync patch script](https://github.com/Frogging-Family/wine-tkg-git/blob/c15b9c448bf101a3bf32bf15ee852199e5d430d1/wine-tkg-git/wine-tkg-patches/proton/fsync/fsync): more explicitly split patches into two blocks - before and after 5.20 (for versions before 5.20, bring checks to the current common style.)
- `_fsync_futex_waitv` already enabled by default since https://github.com/Frogging-Family/wine-tkg-git/commit/764ff67d6fd7aad4edc3d03d7d46d69c6bbd07ff . So let's just stick this to fsync-unix patches as the official fsync version (for wine-5.20+) and remove unnecessary checks. 
- allow build (for wine-5.20+) with …
=> fsync: Rename toggle options

wine-tkg-git/wine-tkg-scripts/build-32.sh
This change was also needed on gentoo which uses /usr/lib instead of /usr/lib32.
Untested on other distros using /usr/lib.
=> Fix proton 8 on distros using /usr/lib

wine-tkg-git/wine-tkg-scripts/wine-tkg, wine-tkg-git/wine-tkg-scripts/wine-tkg-interactive, wine-tkg-git/wine-tkg-scripts/wine64-tkg
There were three issues in the starting scripts `bin/wine-tkg`, `bin/wine64-tkg`, `bin/wine-tkg-interactive` that are packaged with a complete wine-tkg.
- The `PATH` and `LD_LIBRARY_PATH` variables were not exported. That means the variables were not passed down to the wine binary and therefore were not doing anything.
- The ascii frog image printed at startup was printed to stdout. This caused the frog to be part of every script output that used wine, so wine-tkg could not be used in scripts. This issue was solved by printing the frog to stderr instead.
- There were no quotes around the `${@:1}` parameter given to wine. This caused any quotes around arguments to be stripped, so arguments with spaces would not work. Example: `wine-tkg cmd /c echo "a & echo b"` should print `a & echo b` …
=> Fix tkg starting scripts

wine-tkg-git/wine-tkg-patches/hotfixes/valve/de-steamify-80-be.mypatch, wine-tkg-git/wine-tkg-patches/hotfixes/valve/de-steamify-80-exp.mypatch, wine-tkg-git/wine-tkg-patches/hotfixes/valve/hotfixes
compared to the initial 8.0 patches:
- https://github.com/ValveSoftware/wine/commit/5e2c6582eb763f2600af60f6e8eb03a4c11f3f6a left it in, doesn't revert cleanly on latest bleeding-edge anymore
- https://github.com/ValveSoftware/wine/commit/87a85d50c502f705eeaf7a9f3f4c9e54c707ae56 left it in, can be useful and it's not steam specific
- patches split up between valve, valve-exp, valve-exp-bleeding presets now
reverted commits list
```
9b9fd5eb1006cc3f2e12667a7cf45c7a6affa94d
7ad552e281600825a3046005b3ae60c0e1eea49b
d472faa571c4611ccc7a273b57cf053dfdd9ddfb
d78c8ed306c5da9ce35e488358fd4274cc59f3ab
762ca38cf350f01e813ad97459826941a5b77c1e
84b39d3aef9a63e3bc46f3142786fcd7f7aca849
89631f2bf0cd5a1dd4a075c50db2fc365442b3c3
a3f687c45dff423b27dcda55fe1a7175d435547b …
```
=> Hotfixes: Update Proton 8.0 de-steamify patches

wine-tkg-git/wine-tkg-patches/hotfixes/earlyhotfixer
It's currently broken in this case because it causes an error when running a 32-bit application in the WoW64 mode :frog:
Note: I targeted a high enough commit because I doubt WoW64 works on Wine v7.20 well enough to be usable
=> Disable syscall emu patchset on WoW64 builds

wine-tkg-git/wine-tkg-scripts/build-32.sh, wine-tkg-git/wine-tkg-scripts/build-64.sh
Wine commit b1f59bc679a8c2dea18a6789a5b9b1a1ae825129 made some changes to how CC variables work, so we have to set it for the individual architectures now
This also sets the i386 variable for 64-bit-only WoW64 builds (this is because of the way new-style WoW64 builds work)
=> Fix ccache not being set on newer Wine versions/WoW64

wine-tkg-git/wine-tkg-patches/misc/steam/steam
The bug report linked in the patch file reveals that the bug has been fixed a long time ago, so update the patch target accordingly
I also confirmed that Steam works on regular wine-staging too, so this patch definitely isn't necessary :frog:
=> Skip the Steam patch on new enough trees

wine-tkg-git/wine-tkg-patches/hotfixes/rdr2/0001-proton-bcrypt_rdr2_fixes6.mypatch, wine-tkg-git/wine-tkg-patches/hotfixes/rdr2/0002-bcrypt-Add-support-for-calculating-secret-ecc-keys2.mypatch, wine-tkg-git/wine-tkg-patches/hotfixes/rdr2/0003-bcrypt-Add-support-for-OAEP-padded-asymmetric-key-de3.mypatch, wine-tkg-git/wine-tkg-patches/hotfixes/rdr2/hotfixes
Pulled from Proton-8.0 tree.
I hope I haven't messed anything up!
I choose wine-8.10  `68a3b0077e64d1b5232ff75996b82766bcc64ced` as the commit, which seems to work with the new and the old versions of the patch. So it should be good :frog: 
The unconventional inverted ancestor check is hopefully ok. :grimacing: 
Pretty cool that we don't need any reverts here anymore!
=> Hotfixes: Update Proton Bcrypt patches for RDR2

wine-tkg-git/wine-tkg-scripts/build-32.sh
a24a407563a11a40680ffe694088b52a202fa5ab for Debian/Ubuntu
It fixes Proton 8.0 gstreamer build on Debian/Ubuntu, tested on Ubuntu 22.04
=> Fix debuntu Proton 8.0 gstreamer detection

wine-tkg-git/wine-tkg-scripts/build.sh
This fixes installation scripts such as winetricks and setup_dxvk for WoW64 builds that don't have the wine64 binary in them. Of course, this should be fixed on the side of the scripts themselves, but for now I suggest create symlink to make life easier for users.
=> Add wine64 symlink for WoW64 builds

wine-tkg-git/wine-tkg-patches/proton/LAA/LAA, wine-tkg-git/wine-tkg-profiles/advanced-customization.cfg
Large Address Aware seems to be not adapted to work with WoW64, so it causes an error during runtime: 
`wine client error:1a8: sendmsg: Bad file descriptor`
So I suggest disabling it for all WoW64 builds until it is fixed (probably?).
=> Disable LAA patch for WoW64 builds

wine-tkg-git/wine-tkg-scripts/build.sh
Indeed when you want to move the construction or share it, the link is no longer correct.
Before:
```
$ ls -la .
-rwxr-xr-x 1 iroalexis wheel  16488 Aug 12 14:21 wine
lrwxrwxrwx 1 iroalexis wheel    110 Aug 12 14:23 wine64 -> /home/iroalexis/projects/wine-tkg-git/wine-tkg-git/wine-tkg-clean-mainline-git-8.13.r343.gb2a099b3cee/bin/wine
```
Now
```
$ ls -la .
-rwxr-xr-x 1 iroalexis wheel  16488 Aug 12 14:00 wine
lrwxrwxrwx 1 iroalexis wheel      4 Aug 12 14:02 wine64 -> wine
```
=> Use relative path instead of absolute path

wine-tkg-git/wine-tkg-scripts/build.sh
I forgot the PKGBUILD build even if it's less serious but it's cleaner and adopts the same behavior as Wine's tools (winecpp for example) :frog:
=> Adjust wine64 symlink fix for use it too into PKGBUILD

wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-mainline.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-protonify.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-staging-protonify.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-staging.patch
Change ntsync5 non-staging version because is based on slighly older version
Also fix the staging version by adding the "server_protocol.h" file to the patch files
=> ntsync5: Update all ntsync5 patch files

proton-tkg/proton_template/gstreamer.sh
Fixing a gstreamer build with two commits
1: Adding parameters for CFLAGS and CXXFLAGS for GCC 14
2: Using an older version of FFmpeg caused by removing a needed function: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/3378
https://github.com/FFmpeg/FFmpeg/commit/9ee59b63f5ea37700916815538c32dbcadc4a512
=> gstreamer.sh: Fix building cause by GCC 14 and FFmpeg

wine-tkg-git/wine-tkg-patches/misc/fastsync/fastsync, wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-staging-7eb72b7b.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-staging-protonify-7eb72b7b.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync-config.h.in-alt.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync-config.h.in-org.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-staging-protonify.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-staging.patch
For some reason autoconf is modifying several files, including config.h.in, which causes an error when applying the ntsync5 patch. I added two new patches, ntsync-config.h.in-alt and ntsync-config.h.in-org, which apply the changes depending on the line in config.h.in
=> ntsync5: Fix apply patch when config.h.in is different from upstream

wine-tkg-git/wine-tkg-patches/hotfixes/01-non-patch-hotfixes/hotfixes, wine-tkg-git/wine-tkg-patches/misc/childwindow/childwindow-proton
This PR: https://gitlab.winehq.org/wine/wine/-/merge_requests/5833 was merged caused a regression of winewayland.drv causing a complete freeze when started with DISPLAY= . Also update childwindow-proton script to apply legacy patch when _wayland_driver is set to true
=> hotfix: Revert win32u changes when _wayland_driver set to true

wine-tkg-git/wine-tkg-patches/hotfixes/01-non-patch-hotfixes/hotfixes, wine-tkg-git/wine-tkg-patches/hotfixes/hotfixer, wine-tkg-git/wine-tkg-patches/hotfixes/winewayland/hotfixes, wine-tkg-git/wine-tkg-patches/hotfixes/winewayland/winewayland-avoid-crashing.mypatch, wine-tkg-git/wine-tkg-patches/misc/childwindow/childwindow-proton
This patch should fix a problem with winewayland caused by changes in win32u
Also reverse old commit: https://github.com/Frogging-Family/wine-tkg-git/commit/014d66774d5884491b6328075e6cff0d3aa05d3d as it is no longer needed
=> hotfixes: Add new hotfix patch to fix winewayland.drv regression

wine-tkg-git/wine-tkg-patches/misc/fastsync/fastsync, wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-mainline-fd3de90.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-protonify-fd3de90.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-staging-fd3de90.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-staging-protonify-fd3de90.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-mainline.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-protonify.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-staging-protonify.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-staging.patch
This wine PR been merged: https://gitlab.winehq.org/wine/wine/-/merge_requests/5912 and now ntsync5 patches need to be rebase
Should fix this: https://github.com/Frogging-Family/wine-tkg-git/issues/1208
=> ntsync5: Rebase ntsync5 patches and move older version to legacy

wine-tkg-git/wine-tkg-patches/hotfixes/valve/de-steamify-90.mypatch
Valve-exp-bleeding builds have been broken for about a week because a function in ntdll/loader.c has changed, this PR updates the de-steamify-90.mypatch file so it works on the current version.
=> Updated de-steamify-90.mypatch for currentent experimental

proton-tkg/PKGBUILD, wine-tkg-git/PKGBUILD
Wine uses builtin jxrlib for a while now: https://gitlab.winehq.org/wine/wine/-/commit/cfc8f154e5a7a3231db5045d5eac129da1cb638e
=> Remove unnecessary dependency (jxrlib)

wine-tkg-git/wine-tkg-patches/misc/childwindow/childwindow-proton
Child window support has been merged into upstream so the patch is no longer needed: https://gitlab.winehq.org/wine/wine/-/merge_requests/6467
=> childwindow-proton: Skip patch

wine-tkg-git/customization.cfg, wine-tkg-git/wine-tkg-patches/hotfixes/battlenet/hotfixes
In wine-staging, patches to make Battle.net work have been returned: https://gitlab.winehq.org/wine/wine-staging/-/commit/e68e4dbb7529295dc4fde320689f80b1215a0419
The battle-fix patch will not be applied if we are on this commit
I've also redesigned the script to accept the patch only if staging patches are enabled and removed the _battle_fix variable, I think it's better to just apply the patch automatically, considering that it was only removed for two weeks
=> battlenet-fix: Don`t apply patch on staging commit

.github/workflows/proton-arch-nopackage.yml, .github/workflows/proton-ubuntu-nopackage.yml, .github/workflows/proton-valvexbe-arch-nopackage.yml, .github/workflows/wine-arch-ow2test.yml, .github/workflows/wine-arch.yml, .github/workflows/wine-fedora.yml, .github/workflows/wine-ubuntu.yml, .github/workflows/wine-valvexbe-pacman.yml, .github/workflows/wine-valvexbe.yml
As part of implementing better dependency autoresolution, a9d0a33afe ("[IMPROVE] Better deps resolver (#1138)") and ff45a43dd5 ("proton: Enable dependency autoresolver") removed the _nomakepkg_dep_resolution_distro option from customization.cfg and proton-tkg.cfg. However, CI workflows for non-makepkg builds of Wine and Proton still expect to set this option.
In addition, the workflow for Arch makepkg builds of Wine contains a workaround for Frogging-Family/wine-tkg-git#237 that was obviated in part by 37ce946749 ("fix pipewire-jack not providing jack2 anymore on arch linux anymore (#675)") and in part by 4971465b39 ("makepkg: Only grab lib32 deps when _NOLIB32 is set to "false").
Update the currently maintained CI workflows to remove these outdated steps. This shouldn't affect anything, …
=> CI: Remove outdated steps from workflows

wine-tkg-git/wine-tkg-scripts/prepare.sh
Also rework the logic for adding -esync and -fsync to make various conditions for adding these three pkgname components clearer. For example, ntsync can (theoretically) coexist with esync; in that case we would add just -ntsync, not -esync-ntsync (cf. esync and fsync coexistence).
=> Add -ntsync in Wine build pkgname

proton-tkg/proton-tkg.cfg, wine-tkg-git/customization.cfg
ntsync is part of the kernel UAPI, so the presence of the ntsync module on the build host is not required to build Wine with ntsync support. A complete ntsync header file at /usr/include/linux/ntsync.h (replacing, if applicable, the incomplete stub mainlined in kernel 6.10) is sufficient.
Note also that the proposed ntsync patchset targets kernels >= 6.8, but builds still work if the build host is running an earlier kernel. This is most immediately relevant for CI, as the ubuntu-latest GitHub Actions runner has kernel 6.5.
=> Clarify build requirements for NTSync5 in .cfg files

wine-tkg-git/wine-tkg-patches/hotfixes/hotfixer, wine-tkg-git/wine-tkg-patches/hotfixes/legacy_ntdll_writecopy/hotfixes, wine-tkg-git/wine-tkg-patches/hotfixes/legacy_ntdll_writecopy/legacy-ntdll-writecopy.mypatch
Apply this patch when protonify and staging is enabled
Should fix this: https://github.com/Frogging-Family/wine-tkg-git/issues/1265
=> hotfixes: Add new hotfix legacy-ntdll-writecopy

wine-tkg-git/wine-tkg-patches/hotfixes/hotfixer, wine-tkg-git/wine-tkg-patches/hotfixes/shm_esync_fsync/HACK-user32-Always-call-get_message-request-after-waiting.mypatch, wine-tkg-git/wine-tkg-patches/hotfixes/shm_esync_fsync/hotfixes
And enable it if esync/fsync is used on trees containing Wine commit [54ca1ab607d3ff22a1f57a9561430f64c75f0916](https://gitlab.winehq.org/wine/wine/-/commit/54ca1ab607d3ff22a1f57a9561430f64c75f0916).
The patch is just a rebase of [this](https://github.com/ValveSoftware/wine/commit/9ceae59cebd111f0fb06d63ad1495ea1becd714b), which was made to work around the same issue in Proton.
Somebody should make a bug report for wine-staging about this, since it affects non-tkg staging esync as well...
Fixes #1278
=> hotfixes: Add new shm_esync_fsync hotfix to workaround high CPU usage

wine-tkg-git/wine-tkg-patches/hotfixes/NosTale/hotfixes, wine-tkg-git/wine-tkg-patches/hotfixes/NosTale/nostale_mouse_fix-0bfdac7.mypatch
Fix broken builds since Wine upstream 0bfdac7f65
("win32u: Move the PE side DND callbacks to user32.").
Fixes Frogging-Family#1288.
=> Hotfixes: Update NosTale hotfix for 0bfdac7

wine-tkg-git/wine-tkg-scripts/prepare.sh
The Wine version tag with ntsync on is currently "TkG Plain" for mainline and "TkG Staging Esync" for staging builds.
"TkG Plain NTsync" and "TkG Staging NTsync" seem better.
Note that "Esync" shouldn't appear in the tag for staging ntsync builds. It happens because _use_staging="true" also forces _staging_esync="true", which then results in "Esync" being added to the tag even though the staging impl of esync is patched in only temporarily.
=> prepare: Add NTsync version tag

wine-tkg-git/wine-tkg-patches/hotfixes/01-non-patch-hotfixes/hotfixes, wine-tkg-git/wine-tkg-patches/misc/fastsync/fastsync, wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-staging-d7ec9d3.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-staging-protonify-d7ec9d3.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-staging.patch
Rebase ntsync5 patches broken by wine-staging cd2cce28cc ("eventfd_synchronization: Fix compile warnings.").
Also revert the existing hotfix stopgap ecd65dc53a ("staging_fixes: Revert esync patchset for ntsync5 (#1242)").
=> ntsync5: Rebase for wine-staging cd2cce2

wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg/mainline/proton-tkg.patch
When rebasing patches I forgot to add the patch for mailline
Should fix this #1296
=> proton-tkg: Add forgoten patch for mainline

wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-mainline.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-protonify.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-staging.patch
Adds no_get_fast_sync in object.c which I only added in the protonify-staging patch
=> ntsync5: fix crash wineserver

.github/workflows/wine-arch.yml
Since Wine 4db7ed25b9 ("winevulkan: Cache downloaded files in make_vulkan."), Wine builds with Vulkan enabled fail on Arch runners due to insufficient permissions when dlls/winevulkan/make_vulkan attempts to create a cache directory at /home/user/.cache/wine.
Fix the build failure by setting the currently unused XDG_CACHE_HOME envvar to force the cache directory to be created somewhere inside /tmp instead.
This additionally fixes build failures that would otherwise arise in dlls/opencl/make_opencl, dlls/opengl32/make_opengl, and tools/make_unicode, all of which use that envvar to derive the same cache directory path and attempt to create it at build time if it doesn't exist.
Note that dlls/appwiz.cpl/addons.c also references that envvar, but setting it during build time should not affect …
=> CI: Set XDG_CACHE_HOME envvar for Wine builds on Arch

wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-staging-ac1ff67c.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-staging.patch
=> ntsync5: fix ntsync5-staging and legacy patch

wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-mainline.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-protonify.patch
This patches doesn`t have code for completion.c which cause wineserver crash in Battle.Net
Should fix this #1327 and possibly this #1322
=> ntsync5: Fix mainline and protonify patch

wine-tkg-git/wine-tkg-patches/proton/esync/esync, wine-tkg-git/wine-tkg-patches/proton/esync/legacy/esync-unix-mainline-4161e62e.patch
=> esync-mainline: rebase against wine 10.0-rc1

wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-mainline.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-protonify.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-staging-protonify.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-staging.patch
For some reason CachyOS in kernel 6.12.6 update ntsync5 kernel driver to v7 which cause problem
Also fix this: #1343 
These patches are incompatible with past versions
=> ntsync5: Rebase for ntsync5 v7 Kernel Driver

wine-tkg-git/customization.cfg, wine-tkg-git/wine-tkg-patches/misc/fastsync/fastsync, wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-mainline.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-protonify.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-staging-protonify.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-staging.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync7-mainline.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync7-protonify.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync7-staging-protonify.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync7-staging.patch, wine-tkg-git/wine-tkg-scripts/prepare.sh
So far at the moment ntsync5 v7 is only available in linux-cachyos and maybe in others, but ntsync5-dkms from AUR and linux-zen still use the v6 version. So I added ntsync7 patches and a new parameter for `_use_ntsync5`. ntsync5 patches are back to v6
=> ntsync5: Implement ntsync7 support and revert ntsync5 to v6 version

wine-tkg-git/wine-tkg-patches/misc/fastsync/fastsync, wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-mainline-0d7798e8.patch, wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-protonify-0d7798e8.patch
This should solve the problem @sfjuocekr commented on in this pull request: #1345
>This does not apply cleanly to mainline v9.22
=> ntsync5: Add legacy patch for wine v9.22 nonstaging

wine-tkg-git/wine-tkg-patches/hotfixes/binutils/7328.mypatch, wine-tkg-git/wine-tkg-patches/hotfixes/binutils/hotfixes, wine-tkg-git/wine-tkg-patches/hotfixes/hotfixer
I check and this patch didn't cause problem if compile with old binutils like 2.43
=> hotfixes: add hotfix "binutils" for fix building legacy wine with binutils 2.44

wine-tkg-git/wine-tkg-patches/hotfixes/hotfixer, wine-tkg-git/wine-tkg-patches/hotfixes/makefiles/7371.mypatch, wine-tkg-git/wine-tkg-patches/hotfixes/makefiles/hotfixes
This hotfix fix regression cause by 7620f21ff98a85249b0b110bcba9953b32763f28
Should fix this: #1374 and possibly #1365
=> hotfix: Add new hotfix "makefiles"

wine-tkg-git/wine-tkg-patches/misc/CSMT-toggle/CSMT-toggle.patch
Fixes #1349.
With this patch, I can build wine-staging successfully using GCC 14.2.1 (without additional error suppression flags).
=> Fix `incompatible-pointer-types` error in CSMT-toggle patchset (for GCC 14+)

wine-tkg-git/wine-tkg-patches/misc/enable_dynamic_wow64_def/enable_dynamic_wow64_def, wine-tkg-git/wine-tkg-patches/misc/enable_dynamic_wow64_def/enable_dynamic_wow64_def.patch, wine-tkg-git/wine-tkg-profiles/advanced-customization.cfg, wine-tkg-git/wine-tkg-scripts/prepare.sh
This patch apply when enable wow64 on wine 10.2 and higher. This make WINEARCH=wow64 enable by default
=> Add new patch: enable_dynamic_wow64_def

wine-tkg-git/wine-tkg-scripts/build.sh
Fixes https://github.com/Frogging-Family/wine-tkg-git/issues/1374 for external install with makepkg builds.
=> build.sh: Add _new_makefiles check in _package_makepkg().

wine-tkg-git/PKGBUILD, wine-tkg-git/non-makepkg-build.sh, wine-tkg-git/wine-tkg-scripts/build.sh
Should fix configure since upstream check if lib files in one folder. If is not to give error
For proton-tkg script put lib files in `lib64` folder and create `lib` folder where put symlinks
=> scripts: Package all lib files in one forder

wine-tkg-git/wine-tkg-patches/hotfixes/legacy_ntdll_writecopy/hotfixes
This patch no longer using in proton, now this only apply additional-for-nonstaging.mypatch
=> legacy-ntdll-writecopy: Disable hotfix

wine-tkg-git/wine-tkg-patches/hotfixes/earlyhotfixer
This PR fixes a syntax error caused by a missing parenthesis in earlyhotfixer. 
The issue was preventing the project from building successfully. 
This resolves the typo that broke the build when attempting to fix #1438.
Related to  #1440, #1438
=> earlyhotfixer: fix script

wine-tkg-git/wine-tkg-patches/proton/fsync/fsync, wine-tkg-git/wine-tkg-patches/proton/fsync/fsync_futex_waitv.patch, wine-tkg-git/wine-tkg-patches/proton/fsync/legacy/fsync_futex_waitv-013ec6e.patch
This made it build again. It's just setting a new line number for `AC_CHECK_HEADERS`. Should it be a legacy `fsync_futex_waitv_configure_ac.patch`? Should it be split up? I could add that just point me in the right direction or I could look up how it was done.
This is [the one](https://github.com/wine-mirror/wine/commit/013ec6e652ca1bc94b4bdefd8c577d15857bef68) that's problematic from last week
=> fsync_futex_waitv: fix patch

.github/workflows/proton-arch-ntsync-nopackage.yml
ntsync header no longer need since this part of linux-headers
=> Fix arch linux ntsync build action

proton-tkg/proton-tkg.cfg, wine-tkg-git/customization.cfg, wine-tkg-git/wine-tkg-scripts/build.sh
We build wayland driver long ago since --with-wayland been default looks like between 9.21 and 10.0
Should fix #1502
=> Enable wayland driver by default

wine-tkg-git/wine-tkg-patches/hotfixes/hotfixer, wine-tkg-git/wine-tkg-patches/hotfixes/winewayland/de0fc7fd95074cfdeb032d36246c56247d2bd82b.myrevert, wine-tkg-git/wine-tkg-patches/hotfixes/winewayland/hotfixes
This bug caused by commit de0fc7fd95074cfdeb032d36246c56247d2bd82b (winewayland: Switch client surfaces when presenting)
I found bug in unreal engine games using DXVK and VKD3D.
=> hotfixes: Revert upstream commit causing flickering mangohud in wayland

wine-tkg-git/wine-tkg-patches/misc/fastsync/fastsync
Wine 10.16 already implement ntsync, so script only print warning and continue.
Should fix #1648
=> fastsync: Don't apply patches on Wine 10.16

wine-tkg-git/wine-tkg-patches/hotfixes/shm_esync_fsync/hotfixes
fsync patches is depending on esync and here no reason to check both of them
Should fix #1650
=> hotfixes: Don't try apply hotfix is only fsync set to true
