Frogging-Family/wine-tkg-git

proton-tkg/proton-tkg.sh
wine-tkg-git/non-makepkg-build.sh

This is really just a cosmetic change that gets rid of a useless variable.

wine/proton-tkg: nomakepkg: cosmetic simplification with processing of _EXT_CONFIG_PATH

---

proton-tkg/proton-tkg-profiles/advanced-customization.cfg
proton-tkg/proton-tkg-profiles/sample-external-config.cfg
proton-tkg/proton-tkg.sh
wine-tkg-git/wine-tkg-scripts/prepare.sh

Stumbled upon _dxvk_version in config files, didn't look like it was implemented yet, so i did.
* Must be **release tag**, not git.
* Defaults to "latest"
* Prompts on malformed value

Implement _dxvk_version

---

wine-tkg-git/wine-tkg-scripts/prepare.sh

Don't disable winevulkan_vkGetPhysicalDeviceSurfaceCapabilitiesKHR on staging 23ae4e6+

---

wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-steam-bits.patch

I'm new to Wine, but what little I know about programming, gave me to understand that the "return" was wrong XD

Fix Proton-TKG compiling

---

wine-tkg-git/wine-tkg-patches/proton/fsync-unix-mainline.patch
wine-tkg-git/wine-tkg-patches/proton/fsync-unix-staging.patch

There are spaces that got lost. It is a little bit stressful :sweat_smile:

Fix typo 🐸

---

wine-tkg-git/wine-tkg-patches/hotfixes/hotfixer

Fix the commit id for the 32-bit hotfix

---

proton-tkg/proton-tkg.sh

small oversight from f2f272b07d9afbde8d52a20484c018e98e4c0c10

maybe fix "long standing typo" finally

---

.gitattributes
.gitignore

I make a `.gitattribute` so all `.my*(patch/revert)` files get colored properly on GitHub
Also made a PR for community patches: https://github.com/Frogging-Family/community-patches/pull/57

Add .gitattributes

---

proton-tkg/proton-tkg-profiles/sample-external-config.cfg
proton-tkg/proton-tkg.cfg
wine-tkg-git/customization.cfg
wine-tkg-git/wine-tkg-patches/proton/fsync_futex_waitv.patch
wine-tkg-git/wine-tkg-profiles/sample-external-config.cfg
wine-tkg-git/wine-tkg-scripts/prepare.sh

wine-side part of fsync_futex_waitv https://github.com/Frogging-Family/linux-tkg/pull/342
source: https://github.com/ValveSoftware/wine/pull/128

Add fsync_futex_waitv support

---

wine-tkg-git/wine-tkg-scripts/prepare.sh

git merge-base --is-ancestor is repeated

Remove a blerp in valve_proton_fullscreen_hack-staging.patch application

---

wine-tkg-git/PKGBUILD

partial undo ccb6ec8c6f7f00060108dd27851cec7b624bb117
Fixes https://github.com/Frogging-Family/wine-tkg-git/issues/602
(~~I'm not sure if I fully understand exactly how you want to change this part, so tell me if it needs to be done differently, or just reject this PR.~~ ah nvm, `Allow edits by maintainers` exists)

pkgbuild: Restore conf files

---

proton-tkg/proton-tkg-profiles/sample-external-config.cfg
proton-tkg/proton-tkg.cfg
wine-tkg-git/wine-tkg-patches/misc/fastsync-staging-protonify.patch
wine-tkg-git/wine-tkg-patches/misc/legacy/fastsync-staging-protonify-7e42d0.patch
wine-tkg-git/wine-tkg-scripts/prepare.sh

Required extension for https://github.com/Frogging-Family/wine-tkg-git/pull/618
Fixes build proton-tkg and wine-tkg with `_protonify="true"` option
Fixes https://github.com/Frogging-Family/wine-tkg-git/issues/622

Update fastsync patches for proton-tkg

---

wine-tkg-git/wine-tkg-patches/misc/steam/steam.patch

This was broken before, sorry about that.

Fix steamwebhelper patch

---

proton-tkg/proton-tkg-profiles/sample-external-config.cfg
proton-tkg/proton-tkg.cfg
wine-tkg-git/customization.cfg
wine-tkg-git/wine-tkg-patches/hotfixes/hotfixer
wine-tkg-git/wine-tkg-patches/misc/fastsync/fastsync-clock_monotonic-fixup.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/fastsync-mainline.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/fastsync-staging-protonify.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/fastsync-staging.patch
wine-tkg-git/wine-tkg-profiles/sample-external-config.cfg
wine-tkg-git/wine-tkg-scripts/prepare.sh

wine-side part of winesync/fastsync https://lkml.org/lkml/2021/1/17/312
source: https://repo.or.cz/wine/zf.git/shortlog/refs/heads/fastsync4
Esync/Fsync compatible version of fastsync, based on work @openglfreak

Update fastsync patches

---

wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/fastsync-mainline-f076e5f.patch
wine-tkg-git/wine-tkg-scripts/prepare.sh

`server-Key_State` from Staging was accepted to Upstream
same as https://github.com/Frogging-Family/wine-tkg-git/commit/a95474b84be7febc374e5ce548b3a51d31b953f6

Update fastsync-mainline for f076e5f

---

wine-tkg-git/wine-tkg-patches/hotfixes/a2395ecf/rbernon_pending.mypatch

Update the a2395ecf hotfix with Rémi's pending MR patch

---

wine-tkg-git/wine-tkg-patches/hotfixes/1e35966/gofman_hotfix.mypatch
wine-tkg-git/wine-tkg-patches/hotfixes/1e35966/hotfixes

fixes connection issue for Guild Wars 1 and Guild Wars 2 with patch from Paul Gofman
more info: https://bugs.winehq.org/show_bug.cgi?id=52429

Hotfixes: Add workaround for Guild Wars 1 and Guild Wars 2 login issue on 7.14

---

wine-tkg-git/wine-tkg-patches/hotfixes/a2395ecf/hotfixes
wine-tkg-git/wine-tkg-patches/hotfixes/hotfixer

https://gitlab.winehq.org/wine/wine/-/merge_requests/596 merged

Hotfixes: Disable a2395ecf hotfix on a42b22e0+

---

wine-tkg-git/wine-tkg-patches/hotfixes/1e35966/hotfixes
wine-tkg-git/wine-tkg-patches/hotfixes/hotfixer

https://gitlab.winehq.org/wine/wine/-/merge_requests/602 merged

Hotfixes: Disable 1e35966 hotfix on 7b512161+

---

wine-tkg-git/wine-tkg-patches/proton/shared-gpu-resources/sharedgpures-fences-fshack.patch
wine-tkg-git/wine-tkg-patches/proton/shared-gpu-resources/sharedgpures-fences.patch

Add https://github.com/ValveSoftware/wine/commit/c3edb990858a5a430427e7dd70aea76ecaaad23a
thanks to @Blisto91 for initial report and informing me of the fix.

sharedgpures: Update patchset

---

wine-tkg-git/wine-tkg-scripts/build.sh

Makes PE files compatible with Forza Horizon games, etc.
I've been using this for several months now without any issues.

Wine-tkg-git: Build: Fix PE files in the same way as proton-tkg builds.

---

wine-tkg-git/wine-tkg-patches/proton/shared-gpu-resources/legacy/sharedgpures-fences-8319999.patch
wine-tkg-git/wine-tkg-patches/proton/shared-gpu-resources/shared-gpu-resources

Rebase shared gpu resource for wine git

---

wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg/mainline/legacy/proton-tkg-9e8fbda.patch
wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg/mainline/proton-tkg.patch
wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg/proton-tkg
wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg/staging/legacy/proton-tkg-staging-9e8fbda.patch
wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg/staging/proton-tkg-staging.patch

Update proton-tkg meta patchsets for 9e8fbda and move previous versions to legacy

---

wine-tkg-git/wine-tkg-patches/hotfixes/ow2/hotfixes

fixes https://github.com/Frogging-Family/wine-tkg-git/issues/979 (i think)

Disable 1148 hotfix on staging be92c5d+

---

wine-tkg-git/wine-tkg-patches/hotfixes/valve/de-steamify-80-exp-be.mypatch
wine-tkg-git/wine-tkg-patches/hotfixes/valve/de-steamify-80.mypatch
wine-tkg-git/wine-tkg-patches/hotfixes/valve/hotfixes

valve wine commits reverted:
```
9b9fd5eb1006cc3f2e12667a7cf45c7a6affa94d
7ad552e281600825a3046005b3ae60c0e1eea49b
d472faa571c4611ccc7a273b57cf053dfdd9ddfb
d78c8ed306c5da9ce35e488358fd4274cc59f3ab
762ca38cf350f01e813ad97459826941a5b77c1e
5e2c6582eb763f2600af60f6e8eb03a4c11f3f6a
84b39d3aef9a63e3bc46f3142786fcd7f7aca849
89631f2bf0cd5a1dd4a075c50db2fc365442b3c3
a3f687c45dff423b27dcda55fe1a7175d435547b
77a7990f8f57a0d321934a698eb0c9b27ee50e19
87a85d50c502f705eeaf7a9f3f4c9e54c707ae56
d60d512f5a4baa52e70624ea9eb25e50be750953
653847dd8d2740ee886648e96a3eb20db6a6cbe7
a55c9c74a1ddae88ff300fb8b63e9bc7c7b2d266
92e01e33fe6eb993582ba40e931479d78f4e9d60
5b5785001537dea33fb3aa93b0e0d0a6e4c9b794
890c356dda291442ce73c71976e66f75a75e072d
```
patch turns out a bit different between proton_8.0 and …

Hotfixes: Update de-steamify patchset for Proton 8.0

---

wine-tkg-git/wine-tkg-patches/misc/childwindow/childwindow-proton
wine-tkg-git/wine-tkg-patches/misc/childwindow/childwindow-proton-mainline.patch

There's only one (1) conflict when applying the staging version, so this fixed version should probably work fine :frog:

Add a mainline version of the Proton child window patch

---

wine-tkg-git/wine-tkg-patches/misc/fastsync/fastsync
wine-tkg-git/wine-tkg-patches/misc/fastsync/fastsync-mainline.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/fastsync-staging.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/fastsync-mainline-03c1930.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/fastsync-mainline-7b243af.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/fastsync-staging-03c1930.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/fastsync-staging-7b243af.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/fastsync-staging-protonify-03c1930.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/fastsync-staging-protonify-7b243af.patch

resolves patch applying issue for 8.13 and 8.14

Fastsync: Update patches for 7b243af and 03c1930

---

wine-tkg-git/wine-tkg-patches/misc/fastsync/fastsync
wine-tkg-git/wine-tkg-patches/misc/fastsync/fastsync-mainline.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/fastsync-staging.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/fastsync-mainline-59485f0.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/fastsync-staging-59485f0.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/fastsync-staging-protonify-59485f0.patch
wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-cpu-topology-overrides/legacy/proton-cpu-topology-overrides-59485f0.patch
wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-cpu-topology-overrides/proton-cpu-topology-overrides
wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg/proton-tkg
wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg/staging/legacy/proton-tkg-staging-59485f0.patch

this is a fallout from wine commit 59485f00c917061c097c1805d7fa7f61c380c749

fix fastsync, proton-cpu-topology and proton-tkg-staging

---

wine-tkg-git/wine-tkg-patches/game-specific/sims_3-oldnvidia/legacy/sims_3-oldnvidia-c14de4c.patch
wine-tkg-git/wine-tkg-patches/game-specific/sims_3-oldnvidia/sims_3-oldnvidia
wine-tkg-git/wine-tkg-patches/misc/childwindow/childwindow
wine-tkg-git/wine-tkg-patches/misc/childwindow/childwindow-proton
wine-tkg-git/wine-tkg-patches/misc/childwindow/childwindow-proton.patch
wine-tkg-git/wine-tkg-patches/misc/childwindow/legacy/OPWR-proton-c14de4c.patch
wine-tkg-git/wine-tkg-patches/misc/childwindow/legacy/childwindow-c14de4c.patch
wine-tkg-git/wine-tkg-patches/misc/childwindow/legacy/childwindow-proton-c14de4c.patch
wine-tkg-git/wine-tkg-patches/misc/childwindow/legacy/childwindow-proton-mainline-c14de4c.patch
wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg/mainline/legacy/proton-tkg-c14de4c.patch
wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg/mainline/proton-tkg.patch
wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg/proton-tkg
wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg/proton-tkg-additions.patch
wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg/staging/legacy/proton-tkg-staging-c14de4c.patch
wine-tkg-git/wine-tkg-patches/proton/esync/esync
wine-tkg-git/wine-tkg-patches/proton/esync/legacy/esync-unix-mainline-c14de4c.patch
wine-tkg-git/wine-tkg-patches/proton/esync/legacy/esync-unix-staging-c14de4c.patch
wine-tkg-git/wine-tkg-patches/proton/esync/legacy/esync-unix-staging.patch
wine-tkg-git/wine-tkg-patches/proton/fsync/fsync
wine-tkg-git/wine-tkg-patches/proton/fsync/fsync-unix-mainline.patch
wine-tkg-git/wine-tkg-patches/proton/fsync/legacy/fsync-unix-mainline-c14de4c.patch
wine-tkg-git/wine-tkg-patches/proton/fsync/legacy/fsync-unix-staging-c14de4c.patch

reason:
https://github.com/wine-mirror/wine/commit/c14de4c85e79563f5e859765d0015892ae925cd6
I am sadly too lazy to fix more, because I dont know which patches are even used on current proton or wine builds.
So I mainly focused on the ones I can verify for my own builds.
I hope the patches are correct :sweat_smile:

a few fixes for the DECLSPEC_HIDDEN removal

---

wine-tkg-git/wine-tkg-scripts/deps

Simple fix nomakepkg dependency autoresolver for endeavouros and cachyos

deps: Add endeavouros and cachyos as arch

---

wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-mainline.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-protonify.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-staging-protonify.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-staging.patch

ntsync5 patches been updated: https://repo.or.cz/wine/zf.git/shortlog/refs/heads/ntsync5

Update ntsync5 patches

---

wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg/mainline/legacy/proton-tkg-7a054a4a.patch
wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg/mainline/proton-tkg.patch
wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg/proton-tkg
wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg/staging/legacy/proton-tkg-staging-7a054a4a.patch
wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg/staging/legacy/proton-tkg-staging-nofsync-7a054a4a.patch
wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg/staging/proton-tkg-staging-nofsync.patch

Update proton-tkg patches and move old ones to legacy due to incompatibility with this commit: https://gitlab.winehq.org/wine/wine/-/commit/a5e707f7a1ed7f65ef6484ffcdbf2ee597bad030

Update proton-tkg patches and move old versions to legacy

---

wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-mainline.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-protonify.patch

Should solve that issue: https://github.com/Frogging-Family/wine-tkg-git/issues/1191

ntsync5: Fix ntsync5-mainline and ntsync5-protonify

---

wine-tkg-git/wine-tkg-patches/misc/childwindow/childwindow-proton
wine-tkg-git/wine-tkg-patches/misc/childwindow/childwindow-proton-mainline.patch
wine-tkg-git/wine-tkg-patches/misc/childwindow/childwindow-proton.patch
wine-tkg-git/wine-tkg-patches/misc/childwindow/legacy/childwindow-proton-2a263774.patch
wine-tkg-git/wine-tkg-patches/misc/childwindow/legacy/childwindow-proton-mainline-2a263774.patch

Rebase patches for compatibility with this commit: https://gitlab.winehq.org/wine/wine/-/commit/2a2637743b82031d0039698e116a0d1daf18dc1d

childwindow-proton: Rebase patches and move older version to legacy

---

wine-tkg-git/wine-tkg-patches/misc/childwindow/childwindow-proton
wine-tkg-git/wine-tkg-patches/misc/childwindow/childwindow-proton.patch
wine-tkg-git/wine-tkg-patches/misc/childwindow/legacy/childwindow-proton-e9ca13a6.patch
wine-tkg-git/wine-tkg-patches/misc/childwindow/legacy/childwindow-proton-mainline-e9ca13a6.patch

ignore the brain fart fork name
fixes https://github.com/Frogging-Family/wine-tkg-git/issues/1205

childwindow-proton: rebase, move previous version to legacy, etc etc

---

wine-tkg-git/wine-tkg-patches/proton/esync/esync
wine-tkg-git/wine-tkg-patches/proton/esync/legacy/esync-unix-mainline-fd3de90.patch
wine-tkg-git/wine-tkg-patches/proton/fsync/fsync
wine-tkg-git/wine-tkg-patches/proton/fsync/legacy/fsync-unix-staging-fd3de90.patch

Should fix this: https://github.com/Frogging-Family/wine-tkg-git/issues/1212

Rebase esync, fsync-staging and move older version to legacy

---

wine-tkg-git/wine-tkg-patches/misc/fastsync/fastsync
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-staging-1dfac2a.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-staging-protonify-1dfac2a.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-staging-protonify.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-staging.patch

esync patches in wine-staging have been rebased: https://gitlab.winehq.org/wine/wine-staging/-/commit/7624463e7cce6073c4fa88092672331a7d4ad373

NTsync5: Rebase patches for wine-staging changes

---

wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-cpu-topology-overrides/legacy/proton-cpu-topology-overrides-90d2a17.patch
wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-cpu-topology-overrides/proton-cpu-topology-overrides
wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-cpu-topology-overrides/proton-cpu-topology-overrides.patch

Should fix this: https://github.com/Frogging-Family/wine-tkg-git/issues/1236

proton-cpu-topology-overrides: Rebase patch, script and move older version to legacy

---

wine-tkg-git/wine-tkg-patches/misc/childwindow/childwindow-proton
wine-tkg-git/wine-tkg-patches/misc/childwindow/childwindow-proton.patch
wine-tkg-git/wine-tkg-patches/misc/childwindow/legacy/childwindow-proton-cb1c03b9.patch
wine-tkg-git/wine-tkg-patches/misc/childwindow/legacy/childwindow-proton-mainline-cb1c03b9.patch
wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg/staging/proton-tkg-staging-nofsync.patch

Should fix this: https://github.com/Frogging-Family/wine-tkg-git/issues/1247

childwindow-proton: Rebase patches and other things

---

wine-tkg-git/wine-tkg-patches/misc/childwindow/childwindow-proton
wine-tkg-git/wine-tkg-patches/misc/childwindow/legacy/childwindow-proton-c2d46ea.patch
wine-tkg-git/wine-tkg-patches/misc/childwindow/legacy/childwindow-proton-mainline-c2d46ea.patch

Should fix this: https://github.com/Frogging-Family/wine-tkg-git/issues/1270

childwindow-proton: Rebase legacy patch

---

wine-tkg-git/wine-tkg-patches/proton/fsync/fsync
wine-tkg-git/wine-tkg-patches/proton/fsync/fsync-unix-mainline.patch
wine-tkg-git/wine-tkg-patches/proton/fsync/legacy/fsync-unix-mainline-cebad42.patch
wine-tkg-git/wine-tkg-patches/proton/fsync/legacy/fsync-unix-staging-cebad42.patch

fsync: rebase for cebad42

---

wine-tkg-git/wine-tkg-patches/proton/fsync/fsync
wine-tkg-git/wine-tkg-patches/proton/fsync/fsync-unix-mainline.patch
wine-tkg-git/wine-tkg-patches/proton/fsync/fsync-unix-staging.patch
wine-tkg-git/wine-tkg-patches/proton/fsync/legacy/fsync-unix-mainline-962017be.patch
wine-tkg-git/wine-tkg-patches/proton/fsync/legacy/fsync-unix-staging-962017be.patch

Should fix this #1306 and this #1307

fsync: rebase against 962017beef4a0405e4fece0075e286e445da55da

---

wine-tkg-git/wine-tkg-patches/hotfixes/legacy_ntdll_writecopy/additional-for-nonstaging.mypatch
wine-tkg-git/wine-tkg-patches/hotfixes/legacy_ntdll_writecopy/hotfixes

This patch missing is build without staging patches fix problem with login window for Battle.net #1327

ntdll-WRITECOPY: add additional patch for mainline

---

wine-tkg-git/wine-tkg-patches/proton/fsync/fsync
wine-tkg-git/wine-tkg-patches/proton/fsync/fsync-unix-staging.patch
wine-tkg-git/wine-tkg-patches/proton/fsync/legacy/fsync-unix-mainline-18895d05.patch
wine-tkg-git/wine-tkg-patches/proton/fsync/legacy/fsync-unix-staging-18895d05.patch

Fix wine 10.1, add fsync patches for older versions

---

wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-cpu-topology-overrides/legacy/proton-cpu-topology-overrides-0559442.patch
wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-cpu-topology-overrides/legacy/proton-cpu-topology-overrides-25b93b2.patch
wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-cpu-topology-overrides/proton-cpu-topology-overrides
wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg-steamclient-swap/legacy/proton-tkg-steamclient-swap-4608d8b.patch
wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg-steamclient-swap/proton-tkg-steamclient-swap

Fix proton wine-mainline build

---

proton-tkg/proton_template/conf/proton
wine-tkg-git/PKGBUILD
wine-tkg-git/non-makepkg-build.sh
wine-tkg-git/wine-tkg-scripts/build.sh

This check commit one time and should work with proton-tkg
Should fix #1374 and possibly #1373

PKGBUILD, non-makepkg-build, scripts: Better version of fix makefiles

---

proton-tkg/proton-tkg.sh
wine-tkg-git/wine-tkg-scripts/prepare.sh

use _new_makefiles in proton-tkg.sh to select the right _lib64name. 
Fixes #1380

Add _new_makefiles to proton_tkg_token and proton-tkg.sh

---

wine-tkg-git/customization.cfg
wine-tkg-git/wine-tkg-patches/proton/dxvk_config/dxvk_config

This patch no longer using in Proton since 7.0 so i think me can disable this

dxvk_config: Disable patch on wine 7.02 and higher

---

wine-tkg-git/wine-tkg-patches/misc/fastsync/fastsync
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-mainline-a2ed0c4b.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-protonify-a2ed0c4b.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-staging-a2ed0c4b.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-staging-protonify-a2ed0c4b.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-mainline.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-protonify.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-staging-protonify.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-staging.patch

Another rebase against a2ed0c4ba2c80e5c1f2d91c2bbba2889e7a3271e

ntsync7: rebase patches and move older version to legacy

---

wine-tkg-git/wine-tkg-patches/misc/fastsync/fastsync
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-mainline-4a3203be.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-protonify-4a3203be.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-staging-4a3203be.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-staging-protonify-4a3203be.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-mainline.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-protonify.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-staging-protonify.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-staging.patch

ntsync7: rebase against 4a3203be64c55c5765203db4e396c49754cbcb2e 

---

wine-tkg-git/customization.cfg

Updating link to merge request for ntsync and building with linux 6.14
I think need more correct write

customization.cfg: Update information about ntsync5/7

---

.github/workflows/proton-arch-ntsync-nopackage.yml

It would be nice if we can have ntsync build, although I know we need NTSync patch needed to be available in kernel, we can probably update the readme, so people can know what is required for NTSync to work?

Proton-TKG NTSync build action

---

wine-tkg-git/wine-tkg-patches/misc/fastsync/fastsync
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-mainline-d945eb4d.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-protonify-d945eb4d.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-staging-d945eb4d.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-staging-protonify-d945eb4d.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-mainline.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-protonify.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-staging-protonify.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-staging.patch

ntsync7: rebase against d945eb4d

---

wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg-steamclient-swap/proton-tkg-steamclient-swap.patch

proton-tkg-steamclient-swap: fix patch

---

wine-tkg-git/wine-tkg-patches/hotfixes/earlyhotfixer

earlyhotfixer: Disable broken winedevice-Default_Drivers on 6912feaf

---

wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-steam-bits/proton-steam-bits
wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-steam-bits/proton-steam-bits-non-protonify.patch
wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-tkg/proton-tkg

patches: Potential fix for 1452

---

wine-tkg-git/wine-tkg-patches/misc/fastsync/fastsync
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-mainline-7b17d107.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-mainline-94ed7498.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-protonify-7b17d107.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-protonify-94ed7498.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-staging-94ed7498.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-staging-protonify-94ed7498.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-mainline.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-protonify.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-staging-protonify.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-staging.patch

Only non-staging because wine-staging need rebase

ntsync7: Rebase patches for 94ed7498 and non-staging for 7b17d107

---

wine-tkg-git/wine-tkg-patches/misc/fastsync/fastsync
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-staging-7b17d107.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-staging-protonify-7b17d107.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-staging-protonify.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-staging.patch

ntsync7: Rebase staging patches against 7b17d107

---

wine-tkg-git/customization.cfg
wine-tkg-git/wine-tkg-patches/misc/winewayland/0025-support-older-EGL-headers.patch
wine-tkg-git/wine-tkg-patches/misc/winewayland/0028-hack-winewayland-handle-fractional-scaling.patch
wine-tkg-git/wine-tkg-patches/misc/winewayland/0029-cursor-shape-v1.patch
wine-tkg-git/wine-tkg-patches/misc/winewayland/0030-Avoid-long-types-on-the-Unix-side.patch
wine-tkg-git/wine-tkg-patches/misc/winewayland/0032-winewayland-ensure-egl_display-is-not-EGL_BAD_PARAME.patch
wine-tkg-git/wine-tkg-patches/misc/winewayland/0033-Add-amdxc-implementation.patch
wine-tkg-git/wine-tkg-patches/misc/winewayland/0040-check-if-FSR4_UPGRADE-env-is-nonzero.patch
wine-tkg-git/wine-tkg-patches/misc/winewayland/0041-fixup-winewayland-handle-locking-with-fractional-sca.patch
wine-tkg-git/wine-tkg-patches/misc/winewayland/0044-minor-formatting-fix.patch
wine-tkg-git/wine-tkg-patches/misc/winewayland/winewayland

Add patches related to fractional scaling and FSR 4

wine-tkg-patches: Add additional GE patches for winewayland

---

wine-tkg-git/wine-tkg-patches/hotfixes/valve/de-steamify-10.0-be.mypatch
wine-tkg-git/wine-tkg-patches/hotfixes/valve/de-steamify-10.0.mypatch
wine-tkg-git/wine-tkg-patches/hotfixes/valve/hotfixes

hotfixes: Fix broken proton based wine.

---

wine-tkg-git/wine-tkg-patches/hotfixes/valve/fixes/0001-revert-icu-proton.mypatch
wine-tkg-git/wine-tkg-patches/hotfixes/valve/hotfixes

hotfixes: Add revert-icu-proton patch

---

wine-tkg-git/wine-tkg-patches/proton/proton-mf-patch/gstreamer-patch1.patch
wine-tkg-git/wine-tkg-patches/proton/proton-mf-patch/gstreamer-patch2.patch
wine-tkg-git/wine-tkg-patches/proton/proton-mf-patch/legacy/gstreamer-patch1-7f833db1.patch
wine-tkg-git/wine-tkg-patches/proton/proton-mf-patch/legacy/gstreamer-patch2-7f833db1.patch
wine-tkg-git/wine-tkg-patches/proton/proton-mf-patch/proton-mf-patch
wine-tkg-git/wine-tkg-scripts/prepare.sh

proton-mf-patches: Add new Proton 10 MF patches for Wine 10.0+

---

wine-tkg-git/wine-tkg-patches/proton/proton-mf-patch/gstreamer-patch2-non-staging.patch
wine-tkg-git/wine-tkg-patches/proton/proton-mf-patch/proton-mf-patch

proton-mf-patch: Add patch part 2 for plain/non-staging

---

wine-tkg-git/wine-tkg-patches/misc/fastsync/fastsync
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-mainline-abf74f5c.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-protonify-abf74f5c.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-staging-abf74f5c.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-staging-protonify-abf74f5c.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-mainline.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-protonify.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-staging-protonify.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-staging.patch

ntsync7: rebase against abf74f5c and move older version to legacy

---

wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-cpu-topology-overrides/legacy/proton-cpu-topology-overrides-e397ed18.patch
wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-cpu-topology-overrides/proton-cpu-topology-overrides
wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-cpu-topology-overrides/proton-cpu-topology-overrides.patch

proton-cpu-override: Rebase against e397ed18 

---

wine-tkg-git/wine-tkg-scripts/prepare.sh

Don't apply esync patches if ntsync is using

---

wine-tkg-git/wine-tkg-patches/hotfixes/valve/de-steamify-10.0-be.mypatch

Some minor things changed in wine.inf.in and caused the patch to fail to apply.

Updated de-steamify-10.0-be.mypatch for current bleeding-edge

---

wine-tkg-git/wine-tkg-patches/proton/LAA/LAA
wine-tkg-git/wine-tkg-patches/proton/LAA/LAA-unix-wow64.patch
wine-tkg-git/wine-tkg-patches/proton/LAA/legacy/LAA-unix-staging-wow64-ea19c06.patch
wine-tkg-git/wine-tkg-patches/proton/LAA/legacy/LAA-unix-wow64-ea19c06.patch

see https://github.com/wine-mirror/wine/commit/ea19c0604abe4c8b41e45a8759e4f335c5d0c50d

LAA: rebase wow64 patches

---

proton-tkg/proton_template/gstreamer.sh

Potential fix gstreamer build for proton-tkg

---

proton-tkg/proton_template/gstreamer.sh

Fix fail build of 32bit gstreamer for proton-tkg

---

wine-tkg-git/wine-tkg-patches/proton/LAA/LAA
wine-tkg-git/wine-tkg-patches/proton/LAA/LAA-unix-staging-wow64.patch
wine-tkg-git/wine-tkg-patches/proton/LAA/LAA-unix-wow64.patch
wine-tkg-git/wine-tkg-patches/proton/LAA/legacy/LAA-unix-staging-wow64-e377b74.patch
wine-tkg-git/wine-tkg-patches/proton/LAA/legacy/LAA-unix-wow64-e377b74.patch

LAA: Rebase laa-wow64 patches

---

wine-tkg-git/wine-tkg-patches/proton/proton-winevulkan/legacy/proton10-winevulkan-6a663cc9.patch
wine-tkg-git/wine-tkg-patches/proton/proton-winevulkan/proton-winevulkan
wine-tkg-git/wine-tkg-patches/proton/proton-winevulkan/proton10-winevulkan.patch

proton10-winevulkan: Rebase against 6a663cc9

---

wine-tkg-git/wine-tkg-patches/misc/fastsync/fastsync
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-mainline-cbb1247f.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-protonify-cbb1247f.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-staging-cbb1247f.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-staging-protonify-cbb1247f.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-mainline.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-protonify.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-staging-protonify.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-staging.patch

ntsync: Rebase against cbb1247f 

---

wine-tkg-git/wine-tkg-patches/misc/fastsync/fastsync
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-mainline-ca95da9c.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-protonify-ca95da9c.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-staging-ca95da9c.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-staging-protonify-ca95da9c.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-mainline.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-protonify.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-staging-protonify.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-staging.patch

ntsync: Rebase against ca95da9c 

---

wine-tkg-git/wine-tkg-patches/proton/esync/esync
wine-tkg-git/wine-tkg-patches/proton/esync/esync-unix-mainline.patch
wine-tkg-git/wine-tkg-patches/proton/esync/esync-unix-staging.patch
wine-tkg-git/wine-tkg-patches/proton/esync/legacy/esync-unix-mainline-ca95da9c.patch
wine-tkg-git/wine-tkg-patches/proton/esync/legacy/esync-unix-staging-ca95da9c.patch
wine-tkg-git/wine-tkg-patches/proton/fsync/fsync
wine-tkg-git/wine-tkg-patches/proton/fsync/fsync-unix-staging.patch
wine-tkg-git/wine-tkg-patches/proton/fsync/legacy/fsync-unix-staging-03516422.patch

Also rebase staging fsync patch against 03516422
Should help #1638

esync: Rebase against ca95da9c

---

wine-tkg-git/wine-tkg-patches/misc/fastsync/fastsync
wine-tkg-git/wine-tkg-patches/misc/fastsync/inproc-sync.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/inproc-sync-bcd3e1a4.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-mainline-2c2f3f15.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/legacy/ntsync5-protonify-2c2f3f15.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-mainline.patch
wine-tkg-git/wine-tkg-patches/misc/fastsync/ntsync5-protonify.patch

ntsync and inproc-sync: Rebase against 2c2f3f15

---

wine-tkg-git/wine-tkg-patches/proton-tkg-specific/proton-sdl-joy/proton10-sdl-joy.patch

This include some `hidclass` and proton-input related patches

proton-sdl-joy: Add additional patches inside proton10-sdl-joy.patch
